def test_number_to_words(number_to_words):
    assert number_to_words(0) == "Zero"
    assert number_to_words(1) == "One"
    assert number_to_words(5) == "Five"
    assert number_to_words(9) == "Nine"
    assert number_to_words(10) == "Ten"
    assert number_to_words(11) == "Eleven"
    assert number_to_words(15) == "Fifteen"
    assert number_to_words(19) == "Nineteen"
    assert number_to_words(20) == "Twenty"
    assert number_to_words(30) == "Thirty"
    assert number_to_words(50) == "Fifty"
    assert number_to_words(90) == "Ninety"
    assert number_to_words(21) == "Twenty One"
    assert number_to_words(35) == "Thirty Five"
    assert number_to_words(48) == "Forty Eight"
    assert number_to_words(99) == "Ninety Nine"
    assert number_to_words(100) == "One Hundred"
    assert number_to_words(200) == "Two Hundred"
    assert number_to_words(500) == "Five Hundred"
    assert number_to_words(900) == "Nine Hundred"
    assert number_to_words(123) == "One Hundred Twenty Three"
    assert number_to_words(456) == "Four Hundred Fifty Six"
    assert number_to_words(789) == "Seven Hundred Eighty Nine"
    assert number_to_words(515) == "Five Hundred Fifteen"  # Test with a "teen" number
    assert number_to_words(210) == "Two Hundred Ten"  # tens only after hundreds
    assert number_to_words(1000) == "One Thousand"
    assert number_to_words(1234) == "One Thousand Two Hundred Thirty Four"
    assert number_to_words(12345) == "Twelve Thousand Three Hundred Forty Five"
    assert number_to_words(123000) == "One Hundred Twenty Three Thousand"
    assert number_to_words(1000000) == "One Million"
    assert number_to_words(1234567) == "One Million Two Hundred Thirty Four Thousand Five Hundred Sixty Seven"
    assert number_to_words(1000000000) == "One Billion"
    assert number_to_words(1234567890) == "One Billion Two Hundred Thirty Four Million Five Hundred Sixty Seven Thousand Eight Hundred Ninety"
    assert number_to_words(100000) == "One Hundred Thousand"
    assert number_to_words(10000000) == "Ten Million"
    assert number_to_words(1001) == "One Thousand One"  # Make sure thousands separators are handled correctly
    assert number_to_words(1010) == "One Thousand Ten" # test 10 case after thousands
    assert number_to_words(1100) == "One Thousand One Hundred"
